---
title: "texas_child_care"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

```{r child_care_data}
# from https://data.texas.gov/Social-Services/HHSC-CCL-Daycare-and-Residential-Operations-Data/bc5r-88dy
# last pulled Jan. 5
child_care_licenses <- read.csv('child_care_licenses.csv')

# requested from HHSC, received Jan. 5
child_care_centers <- read.csv('child_care_centers.csv')

# from https://www.hhs.texas.gov/about/records-statistics/data-statistics/child-care-regulation-statistics
child_care_centers_2021_12 <- read.csv('./raw_csv/child_care_operations_2021_12.csv')

# from https://etss.hhs.texas.gov/t/DAP-RSDA/views/DCMonthlyOperationStatusChanges/WeeklyStatusChanges?%3Aembed=y&%3AisGuestRedirectFromVizportal=y
child_care_centers_2022_01 <- read.csv('./raw_csv/child_care_operations_2022_01.csv')

# county from https://censusreporter.org/data/table/?table=B09001&geo_ids=04000US48,050|04000US48&primary_geo_id=04000US48#
# zip code from https://censusreporter.org/data/table/?table=B09001&geo_ids=04000US48,050|04000US48,860|04000US48&primary_geo_id=04000US48#
children_by_county <- read.csv('children_by_county.csv')
children_by_zip <- read.csv('children_by_zip.csv')
```

```{r}
```

```{r child_care_cleaning}
child_care_licenses <- child_care_licenses %>% 
  mutate(ISSUANCE_DATE = mdy(ISSUANCE_DATE))

child_care_centers <- child_care_centers %>% 
  select(1:11, contains('X.CD_OPRTNG_STTS_')) %>% 
  pivot_longer(cols = starts_with('X.CD_OPRTNG_STTS_'), names_to = 'Week', 
               names_prefix = 'X.CD_OPRTNG_STTS_', values_to = 'Operating_Status') %>% 
  merge(., child_care_centers %>% 
          select(1:11, contains('X.CD_STTS_')) %>% 
          pivot_longer(cols = starts_with('X.CD_STTS_'), names_to = 'Week', 
                       names_prefix = 'X.CD_STTS_', values_to = 'Permit_Status'))

child_care_centers <- child_care_centers %>% 
  mutate(Week = mdy(Week), DT_LCNS_ISSUE = as.Date(as.character(mdy_hms(DT_LCNS_ISSUE)))) %>% 
  arrange(OP_NBR, Week)

child_care_centers$NM_COUNTY[child_care_centers$NM_COUNTY == 'DEAFSMITH'] <- 'DEAF SMITH'

child_care_operations_2021_12 <- child_care_centers_2021_12 %>% 
  rename(OP_NBR = Operation.Number, NBR_REGION = Operation.Region, NM_FCLTY = Operation.Name,
         ADDR_LN1 = Address.Line.1, ADDR_LN2 = Address.Line.2, ADDR_CITY = City, ADDR_ZIP1 = Zip.Code,
         NM_COUNTY = County, OP_TYPE = Operation.Type, NBR_TOTAL_CPCTY = Capacity, 
         DT_LCNS_ISSUE = Permit.Issue.Date) %>% 
  select(1:11, contains('Operating.Status.')) %>% 
  pivot_longer(cols = starts_with('Operating.Status.'), names_to = 'Week', 
               names_prefix = 'Operating.Status.', values_to = 'Operating_Status') %>%
  mutate(DT_LCNS_ISSUE = mdy(DT_LCNS_ISSUE), Week = mdy(Week))
  
child_care_permits_2021_12 <- child_care_centers_2021_12 %>% 
  rename(OP_NBR = Operation.Number, NBR_REGION = Operation.Region, NM_FCLTY = Operation.Name,
         ADDR_LN1 = Address.Line.1, ADDR_LN2 = Address.Line.2, ADDR_CITY = City, ADDR_ZIP1 = Zip.Code,
         NM_COUNTY = County, OP_TYPE = Operation.Type, NBR_TOTAL_CPCTY = Capacity, 
         DT_LCNS_ISSUE = Permit.Issue.Date) %>% 
  select(1:11, contains('Permit.Status.')) %>% 
  pivot_longer(cols = starts_with('Permit.Status.'), names_to = 'Week', 
               names_prefix = 'Permit.Status.', values_to = 'Permit_Status') %>% 
  mutate(DT_LCNS_ISSUE = mdy(DT_LCNS_ISSUE), Week = mdy(Week))

child_care_centers_2021_12 <- bind_cols(child_care_operations_2021_12, child_care_permits_2021_12 %>% 
                                          select(OP_NBR, Week, Permit_Status)) %>% 
  select(-OP_NBR...14, -Week...15) %>% 
  rename(OP_NBR = OP_NBR...1, Week = Week...12) %>% 
  mutate(NBR_REGION = as.integer(NBR_REGION)) %>% 
  filter(OP_NBR != '')

child_care_operations_2022_01 <- child_care_centers_2022_01 %>% 
  rename(OP_NBR = Operation.Number, NBR_REGION = Operation.Region, NM_FCLTY = Operation.Name,
         ADDR_LN1 = Address.Line.1, ADDR_LN2 = Address.Line.2, ADDR_CITY = City, ADDR_ZIP1 = Zip.Code,
         NM_COUNTY = County, OP_TYPE = Operation.Type, NBR_TOTAL_CPCTY = Capacity, 
         DT_LCNS_ISSUE = Permit.Issue.Date) %>% 
  select(1:3, 5:12, contains('Operating.Status.')) %>% 
  pivot_longer(cols = starts_with('Operating.Status.'), names_to = 'Week', 
               names_prefix = 'Operating.Status.', values_to = 'Operating_Status') %>%
  mutate(DT_LCNS_ISSUE = mdy(DT_LCNS_ISSUE), Week = mdy(Week))

child_care_permits_2022_01 <- child_care_centers_2022_01 %>% 
  rename(OP_NBR = Operation.Number, NBR_REGION = Operation.Region, NM_FCLTY = Operation.Name,
         ADDR_LN1 = Address.Line.1, ADDR_LN2 = Address.Line.2, ADDR_CITY = City, ADDR_ZIP1 = Zip.Code,
         NM_COUNTY = County, OP_TYPE = Operation.Type, NBR_TOTAL_CPCTY = Capacity, 
         DT_LCNS_ISSUE = Permit.Issue.Date) %>% 
  select(1:3, 5:12, contains('Permit.Status.')) %>% 
  pivot_longer(cols = starts_with('Permit.Status.'), names_to = 'Week', 
               names_prefix = 'Permit.Status.', values_to = 'Permit_Status') %>%
  mutate(DT_LCNS_ISSUE = mdy(DT_LCNS_ISSUE), Week = mdy(Week))

child_care_centers_2022_01 <- bind_cols(child_care_operations_2022_01, child_care_permits_2022_01 %>% 
                                          select(OP_NBR, Week, Permit_Status)) %>% 
  select(-OP_NBR...14, -Week...15) %>% 
  rename(OP_NBR = OP_NBR...1, Week = Week...12) %>% 
  mutate(NBR_REGION = as.integer(NBR_REGION)) %>% 
  filter(OP_NBR != '')

status <- function(df) {
  df %>% 
    group_by(OP_NBR) %>% 
    arrange(OP_NBR) %>% 
    mutate(Operating_Status = case_when(Operating_Status == '' ~ lag(Operating_Status),
                                      T ~ as.character(Operating_Status)),
           Permit_Status = case_when(Permit_Status == '' ~ lag(Permit_Status),
                                     T ~ as.character(Permit_Status)))
}

for (i in 1:4) {
  child_care_centers_2021_12 <- status(child_care_centers_2021_12)
  child_care_centers_2022_01 <- status(child_care_centers_2022_01)
}

child_care_centers <- child_care_centers %>% 
  bind_rows(., child_care_centers_2021_12, child_care_centers_2022_01) %>% 
  arrange(OP_NBR, Week)
```

```{r child_care_checks}
# check missingness of data per center
child_care_centers %>% 
  group_by(OP_NBR) %>% 
  filter(any(Operating_Status == '' & Permit_Status == ''))

# check missingness of data per week
child_care_centers %>% 
  group_by(Week) %>% 
  count(Operating_Status, Permit_Status) %>% 
  filter(Operating_Status == '' & Permit_Status == '')

# count types of statuses per week
child_care_centers %>% 
  filter(Operating_Status != '' & Permit_Status != '') %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  mutate(pct_n = n / sum(n) * 100)

child_care_centers %>% 
  filter(Operating_Status != '' & Permit_Status != '') %>% 
  group_by(Week) %>% 
  count(Permit_Status) %>% 
  mutate(pct_n = n / sum(n) * 100)

# find centers in operations or permits data, but not licensing data
child_care_centers %>% 
  filter(Week == as.Date('2022-01-01')) %>% 
  mutate(OP_NBR = gsub('-|- | ', '', OP_NBR)) %>% 
  anti_join(., child_care_licenses %>% 
              mutate(OPERATION_NUMBER = gsub('-|- | ', '', OPERATION_NUMBER)),
            by = c('OP_NBR' = 'OPERATION_NUMBER')) %>% 
  count(Operating_Status, Permit_Status)

# find centers in licensing data, but not operating data
child_care_licenses %>% 
  mutate(OPERATION_NUMBER = gsub('-|- | ', '', OPERATION_NUMBER)) %>% 
  anti_join(., child_care_centers %>% 
              filter(Week == as.Date('2021-09-01')) %>% 
              mutate(OP_NBR = gsub('-|- | ', '', OP_NBR)),
            by = c('OPERATION_NUMBER' = 'OP_NBR'))

# count number of operations by type in most recent operating data
child_care_centers %>% 
  filter(Week == as.Date('2022-01-01')) %>% 
  count(OP_TYPE)

# count number of operations by type in licensing data
child_care_licenses %>% 
  count(OPERATION_TYPE)
```

```{r child_care_licenses_analysis}
# count number of licenses issued by month since 1983
child_care_licenses %>% 
  filter(TYPE_OF_ISSUANCE == 'Full Permit' | TYPE_OF_ISSUANCE == 'Initial') %>% 
  count(year(ISSUANCE_DATE), month(ISSUANCE_DATE)) %>% 
  arrange(`year(ISSUANCE_DATE)`, `month(ISSUANCE_DATE)`)
  #arrange(n)

# count number of licenses issued in each county
child_care_licenses %>% 
  count(COUNTY) %>% 
  arrange(desc(n))

# count centers in each county
# find which counties have no licensed centers
child_care_licenses %>% 
  count(COUNTY)
children_by_county %>% 
  mutate(county = toupper(county)) %>% 
  filter(county %in% setdiff(toupper(children_by_county$county), child_care_licenses$COUNTY)) %>% 
  filter(county != 'TEXAS')

# calculate ratio of children under 5 to total capacity of centers in Texas
child_care_licenses %>% 
  summarize(TOTAL_CAPACITY = sum(TOTAL_CAPACITY, na.rm = T)) %>% 
  merge(., children_by_county %>% 
          filter(county == 'Texas')) %>% 
  summarize(under_5 = under_3_years + X3_to_4_years + X5_years, 
            TOTAL_CAPACITY, ratio = under_5 / TOTAL_CAPACITY)

# calculate ratio of children under 5 to total capacity of centers for each county
child_care_deserts <- child_care_licenses %>% 
  group_by(COUNTY) %>% 
  summarize(TOTAL_CAPACITY = sum(TOTAL_CAPACITY, na.rm = T)) %>% 
  merge(., children_by_county %>% 
          filter(county != 'Texas') %>% 
          mutate(county = toupper(county)) %>% 
          rename(COUNTY = county)) %>% 
  summarize(COUNTY, under_5 = under_3_years + X3_to_4_years + X5_years,
            TOTAL_CAPACITY, ratio = under_5 / TOTAL_CAPACITY) %>% 
  arrange(desc(ratio)) %>% 
  filter(ratio >= 3)
```

```{r child_care_operations_analysis}
# count number of fully licensed centers providing care statewide per week
# for graph 'Texas child care centers yet to recover from pandemic closures'
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'Y')

# count number of fully licensed centers "not caring" per county per week
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  group_by(Week, NM_COUNTY) %>% 
  count(Operating_Status) %>% 
  mutate(total = sum(n), pct_not_caring = n / total * 100) %>% 
  filter(Operating_Status == 'N')

# find percent of fully licensed centers providing child care in February 2020
# compare to percent of fully licensed centers providing child care as of January 2022
child_care_centers %>% 
  filter(Permit_Status == 'Full', Week == as.Date('2022-01-01') | Week == as.Date('2020-02-01')) %>% 
  group_by(Week, NM_COUNTY) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'Y') %>% 
  select(Week, NM_COUNTY, pct_caring) %>% 
  ungroup() %>% 
  pivot_wider(names_from = Week, values_from = pct_caring) %>% 
  mutate(diff = `2022-01-01` - `2020-02-01`) %>% 
  filter(diff < 0) %>% 
  merge(., child_care_centers %>% 
          filter(Permit_Status == 'Full', Week == as.Date('2022-02-01')) %>% 
          count(NM_COUNTY) %>% 
          rename(total = n)) %>% 
  mutate(desert = NM_COUNTY %in% child_care_deserts$COUNTY) %>% 
  arrange(diff)

# count types of fully licensed centers "not caring" as of January 2022 and calculate their median capacity
child_care_centers %>% 
  filter(Operating_Status == 'N', Permit_Status == 'Full', Week == as.Date('2022-01-01')) %>% 
  count(OP_TYPE) %>% 
  merge(., child_care_centers %>% 
    filter(Operating_Status == 'N', Permit_Status == 'Full', Week == as.Date('2022-01-01')) %>% 
    group_by(OP_TYPE) %>% 
    summarize(NBR_TOTAL_CPCTY = median(NBR_TOTAL_CPCTY, na.rm = T)))

# calculate ratio of children under 5 to total capacity of centers caring per week for each county
# for graph 'Child care deserts in Texas counties'
child_care_centers %>% 
  filter(Operating_Status == 'Y', Permit_Status == 'Full', NM_COUNTY != '') %>% 
  group_by(Week, NM_COUNTY) %>% 
  summarize(NBR_TOTAL_CPCTY = sum(NBR_TOTAL_CPCTY, na.rm = T)) %>% 
  merge(., children_by_county %>% 
          filter(county != 'Texas') %>% 
          mutate(county = toupper(county)) %>% 
          rename(NM_COUNTY = county)) %>% 
  summarize(Week, NM_COUNTY, under_5 = under_3_years + X3_to_4_years + X5_years, 
            NBR_TOTAL_CPCTY, ratio = under_5 / NBR_TOTAL_CPCTY) %>% 
  filter(Week == as.Date('2022-01-01')) %>% 
  merge(., child_care_centers %>% 
          filter(NM_COUNTY != '', Week == as.Date('2022-01-01')) %>% 
          count(NM_COUNTY, OP_TYPE) %>% 
          pivot_wider(names_from = OP_TYPE, values_from = n))

child_care_centers %>% 
  filter(Operating_Status == 'Y', Permit_Status == 'Full') %>% 
  group_by(Week) %>% 
  summarize(NBR_TOTAL_CPCTY = sum(NBR_TOTAL_CPCTY, na.rm = T)) %>% 
  merge(., children_by_county %>% 
          filter(county == 'Texas') %>% 
          mutate(county = toupper(county)) %>% 
          rename(NM_COUNTY = county)) %>% 
  summarize(Week, under_5 = under_3_years + X3_to_4_years + X5_years, 
            NBR_TOTAL_CPCTY, ratio = under_5 / NBR_TOTAL_CPCTY) %>% 
  select(Week, ratio)

# calculate percent change in number of fully licensed centers providing care from January 1, 2020, by type
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  group_by(OP_TYPE, Week) %>% 
  count(Operating_Status) %>% 
  filter(Operating_Status == 'Y', year(Week) >= 2020) %>% 
  select(-Operating_Status) %>% 
  ungroup() %>% 
  group_by(OP_TYPE) %>% 
  mutate(pct_change = (n - first(n)) / first(n) * 100)

child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  mutate(Type = case_when(grepl('Licensed Center', OP_TYPE) ~ 'Center',
                          grepl('Home', OP_TYPE) ~ 'Home')) %>% 
  group_by(Type, Week) %>% 
  count(Operating_Status) %>% 
  filter(Operating_Status == 'Y', year(Week) >= 2020) %>% 
  select(-Operating_Status) %>% 
  ungroup() %>% 
  group_by(Type) %>% 
  mutate(pct_change = (n - first(n)) / first(n) * 100)

child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  mutate(Type = case_when(grepl('Licensed Center', OP_TYPE) ~ 'Center',
                          grepl('Home', OP_TYPE) ~ 'Home')) %>% 
  filter(Operating_Status == 'Y', year(Week) >= 2020) %>% 
  group_by(Type, Week) %>% 
  summarize(capacity = sum(NBR_TOTAL_CPCTY, na.rm = T))
```

```{r child_care_permits_analysis}
# count number of fully licensed centers per week
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  count(Week) %>% 
  mutate(raw_diff = n - lag(n), pct_diff = (n - lag(n)) / lag(n) * 100)

# count number of new closures per month
child_care_centers %>% 
  filter(Permit_Status == 'Closed') %>% 
  group_by(OP_NBR) %>% 
  slice(1) %>% 
  ungroup() %>% 
  count(year(Week), month(Week))

# check whether any centers reported as full after reporting as closed
child_care_centers %>% 
  group_by(OP_NBR) %>% 
  filter(any(Permit_Status == 'Closed')) %>% 
  merge(., child_care_centers %>% 
          filter(Permit_Status == 'Closed') %>% 
          group_by(OP_NBR) %>%
          slice(tail(row_number(), 1)) %>% 
          mutate(Closure_Date = Week) %>% 
          select(OP_NBR, Closure_Date)) %>% 
  filter(Week >= Closure_Date) %>% 
  count(Permit_Status)

# count number of licenses issued per month
child_care_centers %>% 
  select(-Week, -Operating_Status, -Permit_Status) %>% 
  unique() %>% 
  count(year(DT_LCNS_ISSUE), month(DT_LCNS_ISSUE))
```

```{r before_after_school_analysis}
before_after_schools <- child_care_centers %>% 
  filter(OP_TYPE == 'Licensed Center - Before/After School Program', Permit_Status == 'Full')

# count number of fully licensed centers providing before/after school care statewide per week
# for graph 'Texas before and after school programs hardest hit by pandemic'
before_after_schools %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'Y')

# count number of programs "not caring" per county per week
before_after_schools %>% 
  group_by(Week, NM_COUNTY) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'N')

# count programs in each county as of December 2021
# find which counties have no licensed programs
before_after_schools %>% 
  filter(Week == as.Date('2021-12-01')) %>% 
  count(NM_COUNTY)
children_by_county %>% 
  mutate(county = toupper(county)) %>% 
  filter(county %in% setdiff(toupper(children_by_county$county), 
                             filter(before_after_schools, Week == as.Date('2022-01-01'))$NM_COUNTY)) %>% 
  filter(county != 'TEXAS')

# count number of centers fully licensed for before/after school care statewide per week
before_after_schools %>% 
  count(Week) %>% 
  mutate(raw_diff = n - lag(n), pct_diff = (n - lag(n)) / lag(n) * 100)

# count number of new before/after school program closures per month
child_care_centers %>% 
  filter(OP_TYPE == 'Licensed Center - Before/After School Program', Permit_Status == 'Closed') %>% 
  group_by(OP_NBR) %>% 
  slice(1) %>% 
  ungroup() %>% 
  count(year(Week), month(Week))
```

```{r reporting}
# find centers for Mitchell
child_care_centers %>% 
  filter(Permit_Status == 'Closed') %>% 
  group_by(OP_NBR) %>% 
  slice(1) %>% 
  ungroup() %>% 
  filter(Week >= as.Date('2020-03-01')) %>% 
  filter(NM_COUNTY %in% child_care_deserts$COUNTY) %>% # to find closed centers in deserts
  arrange(desc(NBR_TOTAL_CPCTY)) # to find closed centers with large capacities

child_care_centers %>% 
  filter(Permit_Status == 'Full', Operating_Status == 'Y', Week == as.Date('2022-01-01')) %>% 
  filter(NM_COUNTY %in% child_care_deserts$COUNTY) # to find still open centers in deserts

child_care_centers %>% 
  filter(OP_TYPE == 'Registered Child-Care Home', Permit_Status == 'Full') %>% 
  count(Week) 
```

```{r child_care_viz}
# chart number of child care licenses issued since 1983
child_care_licenses %>% 
  count(year(ISSUANCE_DATE), month(ISSUANCE_DATE)) %>% 
  summarize(date = mdy(paste0(as.character(`month(ISSUANCE_DATE)`), '/01/', `year(ISSUANCE_DATE)`)), n) %>% 
  filter(year(date) >= 2019) %>% 
  ggplot(data = ., mapping = aes(x = date, y = n)) +
  geom_line() +
  theme_classic()

# chart number of fully licensed centers providing child care from January 2019 to December 2021
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  filter(Operating_Status == 'Y') %>% 
  ggplot(data = ., mapping = aes(x = Week, y = n)) + 
  geom_line() +
  theme_classic()

# chart percent of fully licensed centers providing child care from January 2019 to December 2021
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'Y') %>% 
  ggplot(data = ., mapping = aes(x = Week, y = pct_caring)) +
  geom_line() +
  theme_classic()

# chart number of fully licensed centers from January 2019 to December 2021
child_care_centers %>% 
  filter(Permit_Status == 'Full') %>% 
  count(Week) %>% 
  ggplot(data = ., mapping = aes(x = Week, y = n)) +
  geom_line() +
  theme_classic()

# chart number of new center closures from January 2019 to December 2021
child_care_centers %>% 
  filter(Permit_Status == 'Closed') %>% 
  group_by(OP_NBR) %>% 
  slice(1) %>% 
  ungroup() %>% 
  count(year(Week), month(Week)) %>% 
  summarize(date = mdy(paste0(as.character(`month(Week)`), '/01/', `year(Week)`)), n) %>% 
  ggplot(data = ., mapping = aes(x = date, y = n)) +
  geom_line() +
  scale_y_continuous(limits = c(0, 500)) +
  theme_classic()

# chart number of fully licensed centers providing before/after school care from January 2019 to December 2021
before_after_schools %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  filter(Operating_Status == 'Y') %>% 
  ggplot(data = ., mapping = aes(x = Week, y = n)) + 
  geom_line() +
  theme_classic()

# chart percent of fully licensed centers providing before/after school care from January 2019 to December 2021
before_after_schools %>% 
  group_by(Week) %>% 
  count(Operating_Status) %>% 
  mutate(pct_caring = n / sum(n) * 100) %>% 
  filter(Operating_Status == 'Y') %>% 
  ggplot(data = ., mapping = aes(x = Week, y = pct_caring)) +
  geom_line() +
  theme_classic()

# chart number of centers fully licensed for before/after school care from January 2019 to December 2021
before_after_schools %>% 
  count(Week) %>% 
  ggplot(data = ., mapping = aes(x = Week, y = n)) +
  geom_line() +
  theme_classic()
```

```{r wage_data}
# from https://www.bls.gov/oes/tables.htm
oes_2020 <- read.csv('oes_2020.csv')
oes_2019 <- read.csv('oes_2019.csv')
oes_2018 <- read.csv('oes_2018.csv')
oes_2017 <- read.csv('oes_2017.csv')
oes_2016 <- read.csv('oes_2016.csv')
oes_2015 <- read.csv('oes_2015.csv')
oes_2014 <- read.csv('oes_2014.csv')
oes_2013 <- read.csv('oes_2013.csv')
oes_2012 <- read.csv('oes_2012.csv')
oes_2011 <- read.csv('oes_2011.csv')
```

```{r wage_cleaning}
# filter for Texas and metropolitan statistical areas in Texas, as well as childcare workers
# 25-2011: preschool teachers, except special education
# 25-2012: kindergarten Teachers, except special education
# 35-3011: bartenders
# 35-3023: fast food and counter workers
# 35-3031: waiters and waitresses
# 39-9011: child care workers
# 41-2031: retail salespersons

oes_2020 <- oes_2020 %>% 
  filter(PRIM_STATE == 'TX', 
         OCC_CODE %in% c('25-2011', '25-2012', '35-3011', '35-3023', '35-3031', '39-9011', '41-2031')) %>% 
  select(-PRIM_STATE, -I_GROUP) %>% 
  mutate(year = 2020)

oes_2019 <- oes_2019 %>% 
  filter(area %in% oes_2020$AREA, occ_code %in% oes_2020$OCC_CODE) %>% 
  rename(jobs_1000 = jobs_1000_orig) %>% 
  select(-i_group) %>% 
  mutate(year = 2019)

colnames(oes_2020) <- colnames(oes_2019)

oes_2018 <- oes_2018 %>% 
  filter(area %in% oes_2020$area, occ_code %in% oes_2020$occ_code) %>% 
  select(-X, -i_group) %>% 
  mutate(year = 2018)

oes_2017 <- oes_2017 %>% 
  filter(area %in% oes_2020$area, occ_code %in% oes_2020$occ_code) %>% 
  select(-X, -i_group) %>% 
  mutate(year = 2017)

oes_2016 <- oes_2016 %>% 
  filter(area %in% oes_2020$area, occ.code %in% oes_2020$occ_code) %>% 
  select(-X) %>% 
  mutate(year = 2016)

oes_2015 <- oes_2015 %>% 
  filter(area %in% oes_2020$area, occ.code %in% oes_2020$occ_code) %>% 
  select(-X) %>% 
  mutate(year = 2015)

oes_2014 <- oes_2014 %>% 
  filter(area %in% oes_2020$area, occ.code %in% oes_2020$occ_code) %>% 
  mutate(year = 2014)

oes_2013 <- oes_2013 %>% 
  filter(area %in% oes_2020$area, occ_code %in% oes_2020$occ_code) %>% 
  mutate(year = 2013)

oes_2012 <- oes_2012 %>% 
  filter(area %in% oes_2020$area, occ_code %in% oes_2020$occ_code) %>% 
  mutate(year = 2012)

oes_2011 <- oes_2011 %>% 
  filter(AREA %in% oes_2020$area, OCC_CODE %in% oes_2020$occ_code) %>% 
  mutate(year = 2011)

colnames(oes_2016) <- colnames(oes_2020)
colnames(oes_2015) <- colnames(oes_2020)
colnames(oes_2014) <- colnames(oes_2020)
colnames(oes_2011) <- colnames(oes_2020)
oes_2019$loc_quotient <- as.character(oes_2019$loc_quotient)

wages <- bind_rows(oes_2011, oes_2012, oes_2013, oes_2014, oes_2015,
          oes_2016, oes_2017, oes_2018, oes_2019, oes_2020) %>% 
  mutate(naics = as.integer(naics), h_mean = as.double(h_mean), 
         a_mean = as.double(gsub(',', '', a_mean)), mean_prse = as.double(mean_prse), 
         h_pct10 = as.double(h_pct10), h_pct25 = as.double(h_pct25), 
         h_median = as.double(h_median), h_pct75 = as.double(h_pct75), 
         a_pct10 = as.double(gsub(',', '', a_pct10)), a_pct25 = as.double(gsub(',', '', a_pct25)), 
         a_median = as.double(gsub(',', '', a_median)), a_pct75 = as.double(gsub(',', '', a_pct75)),
         a_pct90 = as.double(gsub(',', '', a_pct90)))
```

```{r wage_analysis}
wages <- read.csv('wages.csv')

# calculate change in median hourly wage for child care workers in each MSA from 2011 to 2020
wages %>% 
  filter(occ_code == '39-9011') %>% 
  select(year, area, h_median) %>% 
  filter(year == 2011 | year == 2020) %>% 
  pivot_wider(names_from = year, values_from = h_median) %>% 
  mutate(change = `2020` - `2011`) %>% 
  arrange(area) %>% 
  bind_cols(., wages %>% 
              filter(occ_code == '39-9011') %>% 
              arrange(year) %>% 
              slice(1:32) %>%
              select(area_title)) %>% 
  arrange(desc(change))

# compare median hourly wage for each job in each MSA in 2020
wages %>% 
  filter(area != 48) %>% 
  select(year, area, occ_title, a_median) %>% 
  mutate(hourly_median = a_median / (40 * 52)) %>% 
  select(-a_median) %>% 
  filter(year == 2020) %>% 
  left_join(., wages %>% 
              filter(area != 48) %>% 
              arrange(year) %>% 
              slice(1:179) %>% 
              select(area, area_title) %>% 
              unique()) %>% 
  select(area_title, occ_title, hourly_median) %>% 
  group_by(area_title) %>% 
  arrange(desc(hourly_median), .by_group = T) %>% 
  filter(occ_title %in% c('Retail Salespersons', 'Childcare Workers', 
                          'Preschool Teachers, Except Special Education',
                          'Kindergarten Teachers, Except Special Education'))

wages %>% 
  filter(area == 47020, year == 2020) %>% 
  select(occ_title, h_median)

# calculate change in median hourly wage for each job in each MSA from 2011 to 2020
wages %>% 
  filter(area != 48) %>% 
  select(year, area, occ_title, a_median) %>% 
  mutate(hourly_median = a_median / (40 * 52)) %>% 
  select(-a_median) %>% 
  filter(year == 2011 | year == 2020) %>% 
  pivot_wider(names_from = year, values_from = hourly_median) %>% 
  mutate(change = `2020` - `2011`) %>% 
  left_join(., wages %>% 
              filter(area != 48) %>% 
              arrange(year) %>% 
              slice(1:179) %>% 
              select(area, area_title) %>% 
              unique()) %>% 
  select(area_title, occ_title, change) %>% 
  group_by(area_title) %>% 
  arrange(desc(change), .by_group = T) %>% 
  filter(occ_title %in% c('Retail Salespersons', 'Childcare Workers'))

# calculate change in median hourly wage for each job statewide from 2011 to 2020
wages %>% 
  filter(area == 48) %>% 
  select(year, occ_title, a_median) %>% 
  mutate(hourly_median = a_median / (40 * 52)) %>% 
  select(-a_median) %>% 
  pivot_wider(names_from = occ_title, values_from = hourly_median) %>% 
  select(-8)
```

```{r wage_viz}
# visualize median hourly wage for childcare workers from 2011 to 2020
wages %>% 
  filter(area == 48, occ_code == '39-9011') %>% 
  ggplot(data = ., mapping = aes(x = year, y = h_median)) +
  geom_line() +
  scale_x_discrete(limits = c(2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)) +
  scale_y_continuous(limits = c(7.25, 15)) +
  labs(y = 'median hourly wage for child care workers') +
  theme_classic()
```